### ISSUE TITLE
您好，向您请教一个关于模型训练过程中中--src_category  --tgt_category 参数输入的问题，希望您能给出详细一点的解答，谢谢

### ISSUE THREAD

**Issue by love112358** [ChrisAllenMing/Cross_Category_Video_Highlight#3]
您好 ，我在通过你的模型进行网络训练时，有一个疑惑就是关于红色框中的输入，cls src_cls tgt_cls分别代表什么呢 我看了一下源码，他们都是['dog', 'gymnastics', 'parkour', 'skating', 'skiing', 'surfing'] 列表中的其中一个，所以我没有明白Source-only Target-oracle. DA baselines.的区别是啥，或者说怎么得到的，希望您能告诉我 在运行Source-only Target-oracle. DA baselines.的Python命令时，--src_category  --tgt_category 这两个参数应该分别输入什么呢？ 我觉得不可能是将 ['dog', 'gymnastics', 'parkour', 'skating', 'skiing', 'surfing']进行两两组合进行训练，这样的话会产生很多模型。
![image](https://user-images.githubusercontent.com/33959491/133361056-5ce071f9-f110-4d44-8eef-895b30e5dfc9.png)

**Comment by ChrisAllenMing** [comment]
Hi, thanks for your interests in our work. In cross-category video highlight detection, we consider a practical situation where we have **labaled videos on source video category** and **unlabeled videos on target video category**. In such a situation, we would like to explore how to get a good highlight detector for target category using both labeled source videos and unlabeled target videos. Therefore, for the category space ['dog', 'gymnastics', 'parkour', 'skating', 'skiing', 'surfing'], we can indeed have 6*5=30 different video category pairs, and we can set *src_cls* and *tgt_cls* to each of these pairs. For example, in the case of *src_cls=surfing* and *tgt_cls=skiing*, we train the corresponding method (Source-only, DA baselines or DL-VHD) with both labeled surfing videos and unlabeled skiing videos, and finally test the model on skiing videos, which can evaluate how this method transfers the highlight knowledge from surfing to skiing.

**Comment by love112358** [comment]
> Hi, thanks for your interests in our work. In cross-category video highlight detection, we consider a practical situation where we have **labaled videos on source video category** and **unlabeled videos on target video category**. In such a situation, we would like to explore how to get a good highlight detector for target category using both labeled source videos and unlabeled target videos. Therefore, for the category space ['dog', 'gymnastics', 'parkour', 'skating', 'skiing', 'surfing'], we can indeed have 6*5=30 different video category pairs, and we can set _src_cls_ and _tgt_cls_ to each of these pairs. For example, in the case of _src_cls=surfing_ and _tgt_cls=skiing_, we train the corresponding method (Source-only, DA baselines or DL-VHD) with both labeled surfing videos and unlabeled skiing videos, and finally test the model on skiing videos, which can evaluate how this method transfers the highlight knowledge from surfing to skiing.
