### ISSUE TITLE
About the missing videos in YouTube Highlights dataset

### ISSUE THREAD

**Issue by yeliudev** [ChrisAllenMing/Cross_Category_Video_Highlight#5]
Hi @ChrisAllenMing, thanks for your great work on video highlight detection! As far as I know, ~190 videos are missing in the YouTube Highlights dataset currently. May I ask that how did you handle this problem? Thanks!

**Comment by ChrisAllenMing** [comment]
Hi, thanks for your interests in our work! As you said, some video links in the YouTube Highlights dataset does not work currently. In our experiments, we directly dropped those missing ones that did not return a valid video in .mp4 format.

**Comment by yeliudev** [comment]
I see. Thanks for your reply!
